### ISSUE TITLE
A small reminder: Be sure to put restrictions on your Notion-API-Token permissions

### ISSUE THREAD

**Issue by chaoszh** [howznguyen/howz_blog_notion#70]
Calling notion api in browser will leak your token to everyone who visit your blog website. And then they can write/delete your notion database. Be sure that your token is only granted with Read access.

**Comment by chaoszh** [comment]
I think that worth to be mentioned in README since it is quite serious.

**Comment by howznguyen** [comment]
Thank you for that. I'll add that to the README
